### ISSUE TITLE
Clarification on typespec

### ISSUE THREAD

**Issue by yordis** [infinitered/gluegun#398] opened 2018-12-08 03:19 UTC
Hey folks currently we have this https://github.com/infinitered/gluegun/blob/5cd228e7d98b02354b231e16a78a3260625e999e/src/domain/toolbox.ts#L26

Which it means `options` could be `undefined | Options`.

Are you sure this is the correct type?

I am adding `!` everywhere so the compiler stop complaining about the type.

I read from that object all the time even when I didn't pass any options to the command so I am confused why the typespec is telling me that could be `undefined`.

**Comment by jamonholmgren** [comment] 2018-12-09 03:14
I don't think it should be undefined, since it would just be empty object. Let's make that required.

![image](https://user-images.githubusercontent.com/1479215/49693015-7deb5c00-fb1d-11e8-97d3-c3e8fc6c28e8.png)

**Comment by yordis** [comment] 2018-12-10 19:33
Working on it, a lot of changes on test files since they hardcoded `parameters` 😢

**Comment by jamonholmgren** [comment] 2018-12-23 03:01
This is actually a duplicate of #378, so I will close it and we will track it over there. :)

**Closed by jamonholmgren** 2018-12-23 03:01 UTC
Labels: maintenance, planned
